spring:
  application:
    name: squadxml-generator
  config:
    import:
      - optional:classpath:local-overrides.yaml
  cache:
    caffeine:
      spec: expireAfterWrite=10m

  mvc:
    problemdetails:
      enabled: true
    log-resolved-exception: true

authentik:
  base-url: ${AUTHENTIK_BASE_URL:}
  bearer-token: ${AUTHENTIK_BEARER_TOKEN}
